# Generated by Django 6.0.2 on 2026-04-21 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_day', models.PositiveIntegerField(default=8, help_text='Number of periods in a day')),
                ('default_period_duration', models.PositiveIntegerField(default=50, help_text='Default duration of each period in minutes')),
                ('day_start_time', models.TimeField(default=datetime.time(9, 30), help_text='When the academic day starts')),
                ('day_end_time', models.TimeField(default=datetime.time(16, 30), help_text='When the academic day ends')),
                ('lunch_break_after_period', models.PositiveIntegerField(default=4, help_text='After which period number the lunch break occurs')),
                ('lunch_break_duration', models.PositiveIntegerField(default=30, help_text='Lunch break duration in minutes')),
                ('short_break_duration', models.PositiveIntegerField(default=10, help_text='Short break duration between periods in minutes')),
                ('working_days', models.JSONField(default=list, help_text='List of working day numbers [1=Mon, 2=Tue, ..., 7=Sun]')),
            ],
            options={
                'verbose_name': 'Timetable Configuration',
                'verbose_name_plural': 'Timetable Configurations',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_key', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_app', models.CharField(default='global', max_length=50)),
                ('key', models.CharField(max_length=150)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sub_app', 'key'],
                'indexes': [models.Index(fields=['tenant_key', 'sub_app', 'key', 'is_active'], name='configurati_tenant__aad67b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_key', 'sub_app', 'key'), name='unique_config_per_tenant_subapp_key')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_key', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_app', models.CharField(default='global', max_length=50)),
                ('key', models.CharField(max_length=150)),
                ('is_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sub_app', 'key'],
                'indexes': [models.Index(fields=['tenant_key', 'sub_app', 'key', 'is_active'], name='configurati_tenant__9184b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_key', 'sub_app', 'key'), name='unique_flag_per_tenant_subapp_key')],
            },
        ),
    ]
