# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableconfiguration',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_config', to='profile_management.semester'),
        ),
    ]
