# Generated by Django 6.0.2 on 2026-04-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(help_text="Matches Client.schema_name from django-tenants e.g. 'vels', 'anna'", max_length=63)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='featureflag',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='featureflag',
            name='unique_flag_per_tenant_subapp_key',
        ),
        migrations.RemoveIndex(
            model_name='featureflag',
            name='configurati_tenant__9184b5_idx',
        ),
        migrations.RenameField(
            model_name='featureflag',
            old_name='is_enabled',
            new_name='is_enabled_globally',
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureoverride',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='configuration.featureflag'),
        ),
        migrations.RemoveField(
            model_name='featureflag',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='featureflag',
            name='sub_app',
        ),
        migrations.RemoveField(
            model_name='featureflag',
            name='tenant_key',
        ),
        migrations.AlterUniqueTogether(
            name='tenantfeatureoverride',
            unique_together={('flag', 'schema_name')},
        ),
    ]
