# Generated by Django 6.0.2 on 2026-03-27 12:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_multitenant_config_and_feature_flags"),
        (
            "profile_management",
            "0005_facultyprofile_first_name_facultyprofile_last_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periods_per_day",
                    models.PositiveIntegerField(
                        default=8, help_text="Number of periods in a day"
                    ),
                ),
                (
                    "default_period_duration",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Default duration of each period in minutes",
                    ),
                ),
                (
                    "day_start_time",
                    models.TimeField(
                        default=datetime.time(9, 30),
                        help_text="When the academic day starts",
                    ),
                ),
                (
                    "day_end_time",
                    models.TimeField(
                        default=datetime.time(16, 30),
                        help_text="When the academic day ends",
                    ),
                ),
                (
                    "lunch_break_after_period",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="After which period number the lunch break occurs",
                    ),
                ),
                (
                    "lunch_break_duration",
                    models.PositiveIntegerField(
                        default=30, help_text="Lunch break duration in minutes"
                    ),
                ),
                (
                    "short_break_duration",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Short break duration between periods in minutes",
                    ),
                ),
                (
                    "working_days",
                    models.JSONField(
                        default=list,
                        help_text="List of working day numbers [1=Mon, 2=Tue, ..., 7=Sun]",
                    ),
                ),
                (
                    "semester",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_config",
                        to="profile_management.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Configuration",
                "verbose_name_plural": "Timetable Configurations",
            },
        ),
    ]
