# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
import study_materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the study material', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or summary of the material')),
                ('material_type', models.CharField(choices=[('NOTES', 'Lecture Notes'), ('REFERENCE', 'Reference Material'), ('SLIDES', 'Presentation Slides'), ('BOOK', 'E-Book/Textbook'), ('PAPER', 'Research Paper'), ('TUTORIAL', 'Tutorial'), ('OTHER', 'Other')], default='NOTES', help_text='Type of study material', max_length=20)),
                ('file', models.FileField(help_text='Study material file', upload_to=study_materials.models.study_material_file_path)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Publication status', max_length=20)),
                ('vectorization_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of AI vector indexing', max_length=20)),
                ('vector_document_id', models.CharField(blank=True, db_index=True, default='', help_text='External vector document identifier', max_length=255)),
                ('last_indexed_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last successful vector indexing', null=True)),
                ('vector_error_message', models.TextField(blank=True, default='', help_text='Latest vector indexing error message')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times material was viewed')),
                ('download_count', models.IntegerField(default=0, help_text='Number of times material was downloaded')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the material was published', null=True)),
                ('faculty', models.ForeignKey(help_text='Faculty who uploaded the material', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(help_text='Section to which material is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='core.section')),
                ('subject', models.ForeignKey(help_text='Subject for which material is uploaded', on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which download was made', null=True)),
                ('student', models.ForeignKey(help_text='Student who downloaded the material', on_delete=django.db.models.deletion.CASCADE, related_name='material_downloads', to=settings.AUTH_USER_MODEL)),
                ('study_material', models.ForeignKey(help_text='Study material that was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='study_materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Study Material Download',
                'verbose_name_plural': 'Study Material Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(help_text='Student who viewed the material', on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to=settings.AUTH_USER_MODEL)),
                ('study_material', models.ForeignKey(help_text='Study material that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='study_materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Study Material View',
                'verbose_name_plural': 'Study Material Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['subject', 'section', 'status'], name='study_mater_subject_63b71b_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['faculty', 'status'], name='study_mater_faculty_ca437f_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['-uploaded_at'], name='study_mater_uploade_ee386c_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['vectorization_status', 'updated_at'], name='study_mater_vectori_ec8b23_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialdownload',
            index=models.Index(fields=['study_material', 'student'], name='study_mater_study_m_619904_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialdownload',
            index=models.Index(fields=['-downloaded_at'], name='study_mater_downloa_9a819f_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialview',
            index=models.Index(fields=['study_material', 'student'], name='study_mater_study_m_cc3ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialview',
            index=models.Index(fields=['-viewed_at'], name='study_mater_viewed__8742a1_idx'),
        ),
    ]
