# Generated by Django 6.0.2 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last successful vector indexing', null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='vector_document_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='External vector document identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='vector_error_message',
            field=models.TextField(blank=True, default='', help_text='Latest vector indexing error message'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='vectorization_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of AI vector indexing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['vectorization_status', 'updated_at'], name='study_mater_vectori_8a6f29_idx'),
        ),
    ]
