# Generated by Django 6.0.2 on 2026-03-28 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study_materials", "0002_studymaterial_ai_vector_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studymaterial",
            new_name="study_mater_vectori_ec8b23_idx",
            old_name="study_mater_vectori_8a6f29_idx",
        ),
    ]
