# Generated by Django 6.0.2 on 2026-02-06 13:53

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default roles for the system"""
    Role = apps.get_model('core', 'Role')
    
    # Create global roles (not tied to any department)
    default_roles = [
        {
            'name': 'System Administrator',
            'code': 'ADMIN',
            'is_global': True,
            'is_active': True,
            'department': None
        },
        {
            'name': 'Student',
            'code': 'STUDENT',
            'is_global': True,
            'is_active': True,
            'department': None
        },
        {
            'name': 'Faculty',
            'code': 'FACULTY',
            'is_global': True,
            'is_active': True,
            'department': None
        },
        {
            'name': 'Head of Department',
            'code': 'HOD',
            'is_global': True,
            'is_active': True,
            'department': None
        }
    ]
    
    for role_data in default_roles:
        Role.objects.get_or_create(
            code=role_data['code'],
            department=role_data['department'],
            defaults=role_data
        )


def reverse_default_roles(apps, schema_editor):
    """Remove default roles"""
    Role = apps.get_model('core', 'Role')
    Role.objects.filter(
        code__in=['ADMIN', 'STUDENT', 'FACULTY', 'HOD'],
        department=None
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_default_roles),
    ]
