# Generated by Django 6.0.2 on 2026-02-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
