# Generated by Django 4.2.7 on 2026-04-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_school_remove_department_school_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="core.school",
            ),
        ),
    ]
