# Generated by Django 6.0.2 on 2026-02-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('logout', 'User Logout'), ('forced', 'Forced Logout'), ('security', 'Security Reason')], default='logout', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blacklisted_at'],
                'indexes': [models.Index(fields=['token'], name='core_tokenb_token_77467d_idx'), models.Index(fields=['expires_at'], name='core_tokenb_expires_3987f4_idx')],
            },
        ),
    ]
