# Generated by Django 6.0.2 on 2026-04-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_department_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='vision',
            field=models.TextField(blank=True, help_text='Department vision statement'),
        ),
    ]
