# Generated by Django 6.0.2 on 2026-03-27 11:02

from django.db import migrations, models
from django.db.models import F


def set_section_code(apps, schema_editor):
    Section = apps.get_model("core", "Section")
    # Preserve the old uniqueness (course, name, year) by copying name -> code
    Section.objects.all().update(code=F("name"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_permission_rolepermission_userrole"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="section",
            name="code",
            field=models.CharField(default="TEMP", max_length=10),
        ),
        migrations.RunPython(set_section_code, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(default="TEMP", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "code", "year")},
        ),
    ]
