# Generated by Django 6.0.2 on 2026-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_permission_rolepermission_userrole"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="section",
            name="code",
            field=models.CharField(default="TEMP", max_length=10),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(default="TEMP", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "code", "year")},
        ),
    ]
