# Generated by Django 6.0.2 on 2026-04-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_section_unique_together_section_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Final Year — Highest'), (2, 'Second Year'), (3, 'First Year — Lowest')], default=3, help_text='1=Final Year (highest), 2=Second Year, 3=First Year (lowest). Controls room allocation order in auto-scheduler.'),
        ),
    ]
