# Generated by Django 6.0.2 on 2026-05-21 02:03

import django.core.validators
import django.db.models.deletion
import placement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_department_vision"),
        ("profile_management", "0005_facultyprofile_address_facultyprofile_date_of_birth_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_records",
                        to="tenants.client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=255)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to=placement.models.company_logo_path)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("package_range", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name", "is_active"], name="placement_company_active_idx")],
            },
        ),
        migrations.CreateModel(
            name="PlacementDrive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placementdrive_records",
                        to="tenants.client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "drive_type",
                    models.CharField(
                        choices=[("on_campus", "On Campus"), ("off_campus", "Off Campus"), ("pool", "Pool")],
                        max_length=20,
                    ),
                ),
                ("job_role", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("required_skills", models.TextField(blank=True)),
                (
                    "min_cgpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("eligible_batch_year", models.PositiveIntegerField()),
                ("application_deadline", models.DateTimeField()),
                ("drive_date", models.DateTimeField()),
                ("venue", models.CharField(blank=True, max_length=255)),
                (
                    "package_offered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("bond_years", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="drives", to="placement.company"),
                ),
                (
                    "eligible_branches",
                    models.ManyToManyField(blank=True, related_name="placement_drives", to="core.department"),
                ),
            ],
            options={
                "ordering": ["-drive_date"],
                "indexes": [
                    models.Index(fields=["status", "drive_type"], name="place_drive_status_type_idx"),
                    models.Index(fields=["eligible_batch_year", "min_cgpa"], name="place_drive_batch_cgpa_idx"),
                    models.Index(fields=["application_deadline"], name="placement_drive_deadline_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentapplication_records",
                        to="tenants.client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("resume", models.FileField(blank=True, null=True, upload_to=placement.models.application_resume_path)),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("shortlisted", "Shortlisted"),
                            ("interviewed", "Interviewed"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "drive",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="placement.placementdrive"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_applications",
                        to="profile_management.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("student", "drive")},
                "indexes": [
                    models.Index(fields=["status", "drive"], name="place_app_status_drive_idx"),
                    models.Index(fields=["student", "status"], name="place_app_stud_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlacementRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placementround_records",
                        to="tenants.client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("round_number", models.PositiveIntegerField()),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("aptitude", "Aptitude"),
                            ("technical", "Technical"),
                            ("hr", "HR"),
                            ("group_discussion", "Group Discussion"),
                            ("final", "Final"),
                        ],
                        max_length=30,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("instructions", models.TextField(blank=True)),
                (
                    "drive",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rounds", to="placement.placementdrive"),
                ),
            ],
            options={
                "ordering": ["round_number"],
                "unique_together": {("drive", "round_number")},
                "indexes": [models.Index(fields=["drive", "round_number"], name="placement_round_drive_num_idx")],
            },
        ),
        migrations.CreateModel(
            name="RoundResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roundresult_records",
                        to="tenants.client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail"), ("pending", "Pending")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("interviewer_notes", models.TextField(blank=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_results",
                        to="placement.studentapplication",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="placement.placementround"),
                ),
            ],
            options={
                "unique_together": {("application", "round")},
                "indexes": [models.Index(fields=["round", "result"], name="placement_result_round_idx")],
            },
        ),
        migrations.CreateModel(
            name="PlacementOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placementoffer_records",
                        to="tenants.client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("offer_letter", models.FileField(blank=True, null=True, upload_to=placement.models.offer_letter_path)),
                (
                    "ctc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("joining_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="placement.studentapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentPlacementProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentplacementprofile_records",
                        to="tenants.client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("resume", models.FileField(blank=True, null=True, upload_to=placement.models.student_resume_path)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("portfolio_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("is_placed", models.BooleanField(default=False)),
                (
                    "placed_package",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "placed_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placed_students",
                        to="placement.company",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_profile",
                        to="profile_management.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["student__register_number"],
            },
        ),
    ]
