# Generated by Django 5.2.7 on 2026-05-22 16:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_department_vision"),
        ("placement", "0001_initial"),
        (
            "profile_management",
            "0005_facultyprofile_address_facultyprofile_date_of_birth_and_more",
        ),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="placementdrive",
            options={
                "ordering": ["-drive_date"],
                "verbose_name": "Placement Drive",
                "verbose_name_plural": "Placement Drives",
            },
        ),
        migrations.AlterModelOptions(
            name="placementoffer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Placement Offer",
                "verbose_name_plural": "Placement Offers",
            },
        ),
        migrations.AlterModelOptions(
            name="placementround",
            options={
                "ordering": ["round_number"],
                "verbose_name": "Placement Round",
                "verbose_name_plural": "Placement Rounds",
            },
        ),
        migrations.AlterModelOptions(
            name="roundresult",
            options={
                "verbose_name": "Round Result",
                "verbose_name_plural": "Round Results",
            },
        ),
        migrations.AlterModelOptions(
            name="studentapplication",
            options={
                "ordering": ["-applied_at"],
                "verbose_name": "Student Application",
                "verbose_name_plural": "Student Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="studentplacementprofile",
            options={
                "ordering": ["student__register_number"],
                "verbose_name": "Student Placement Profile",
                "verbose_name_plural": "Student Placement Profiles",
            },
        ),
        migrations.AlterUniqueTogether(
            name="placementround",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="roundresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="studentapplication",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="company",
            name="average_package",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_returning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="tier",
            field=models.CharField(
                choices=[
                    ("dream", "Dream"),
                    ("super_dream", "Super Dream"),
                    ("mass", "Mass Recruiter"),
                ],
                default="mass",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="placementdrive",
            name="category",
            field=models.CharField(
                choices=[
                    ("dream", "Dream"),
                    ("super_dream", "Super Dream"),
                    ("regular", "Regular"),
                ],
                default="regular",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="placementdrive",
            name="eligible_courses",
            field=models.ManyToManyField(
                blank=True, related_name="placement_drives", to="core.course"
            ),
        ),
        migrations.AddField(
            model_name="placementdrive",
            name="experience_type",
            field=models.CharField(
                choices=[
                    ("internship", "Internship"),
                    ("fulltime", "Full-time"),
                    ("contract", "Contract"),
                ],
                default="fulltime",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="placementdrive",
            name="max_applications",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementdrive",
            name="vacancy_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementdrive",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "On-site"),
                ],
                default="onsite",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="placementoffer",
            name="offer_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementoffer",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="placementround",
            name="conducted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_rounds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="placementround",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementround",
            name="is_eliminatory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="placementround",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="placementround",
            name="mode",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("hybrid", "Hybrid"),
                ],
                default="offline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="roundresult",
            name="evaluated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluated_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="interviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="shortlisted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentplacementprofile",
            name="no_of_offers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentplacementprofile",
            name="opted_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentplacementprofile",
            name="preferred_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentplacementprofile",
            name="willing_to_relocate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="placementdrive",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="placementoffer",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="placementround",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="roundresult",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="roundresult",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="studentplacementprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="tenants.client",
            ),
        ),
        migrations.AddIndex(
            model_name="placementoffer",
            index=models.Index(
                fields=["is_accepted"], name="placement_offer_accepted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roundresult",
            index=models.Index(
                fields=["application", "round"], name="placement_result_app_round_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentplacementprofile",
            index=models.Index(
                fields=["is_placed", "placed_company"],
                name="place_profile_placed_co_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="placementround",
            constraint=models.UniqueConstraint(
                fields=("drive", "round_number"), name="unique_drive_round_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="roundresult",
            constraint=models.UniqueConstraint(
                fields=("application", "round"), name="unique_application_round_result"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentapplication",
            constraint=models.UniqueConstraint(
                fields=("student", "drive"), name="unique_student_drive_application"
            ),
        ),
    ]
