# Generated by Django 6.0.2 on 2026-02-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_studentprofile_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('register_number', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.PositiveIntegerField(default=1)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('academic_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PASSED', 'Passed'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('id_proof_type', models.CharField(blank=True, choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport')], max_length=20, null=True)),
                ('id_proof_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.department')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='profile_management.studentprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['register_number'], name='profile_man_registe_089302_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['academic_status'], name='profile_man_academi_8b6a5d_idx'),
        ),
    ]
