# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.CharField(help_text="e.g., '2024-25'", max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Only one academic year can be current')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(choices=[(1, 'Odd Semester'), (2, 'Even Semester')], help_text='1 = Odd Semester, 2 = Even Semester')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Only one semester can be current')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='profile_management.academicyear')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['-academic_year__start_date', 'number'],
                'unique_together': {('academic_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('register_number', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.PositiveIntegerField(default=1)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('academic_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PASSED', 'Passed'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('id_proof_type', models.CharField(blank=True, choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport')], max_length=20, null=True)),
                ('id_proof_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Current GPA (calculated from assignment grades)', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.department')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='profile_management.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ParentLoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_otps', to='profile_management.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(help_text='e.g., Assistant Professor, HOD', max_length=100)),
                ('qualifications', models.TextField(help_text='e.g., Ph.D. in Computer Science, M.Tech')),
                ('specialization', models.CharField(help_text='Area of expertise', max_length=200)),
                ('joining_date', models.DateField()),
                ('office_hours', models.CharField(blank=True, help_text='e.g., Mon-Wed 2-4 PM', max_length=200)),
                ('teaching_load', models.PositiveIntegerField(default=0, help_text='Hours per week')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='faculty_profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joining_date'],
                'indexes': [models.Index(fields=['department', 'is_active'], name='profile_man_departm_9bc629_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(limit_choices_to={'role__code': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='in_charge_sections', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_charge_history', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_incharges', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Section In-Charge',
                'verbose_name_plural': 'Section In-Charges',
                'ordering': ['-semester__start_date', 'section'],
                'indexes': [models.Index(fields=['section', 'semester'], name='profile_man_section_75d199_idx'), models.Index(fields=['faculty', 'semester'], name='profile_man_faculty_3c2626_idx')],
                'unique_together': {('section', 'semester')},
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['register_number'], name='profile_man_registe_089302_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['academic_status'], name='profile_man_academi_8b6a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='parentloginotp',
            index=models.Index(fields=['student', 'code'], name='profile_man_student_4dd2de_idx'),
        ),
    ]
