# Generated by Django 4.2.7 on 2026-04-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_department_school"),
        ("profile_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyprofile",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faculties",
                to="core.department",
            ),
        ),
    ]
