# Generated by Django 5.0.2 on 2026-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_management", "0002_academicyear_parentloginotp_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="current_gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current GPA (calculated from assignment grades)",
                max_digits=3,
                null=True,
            ),
        ),
    ]
