# Generated by Django 5.0.2 on 2026-02-25 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_tokenblacklist"),
        ("profile_management", "0003_studentprofile_current_gpa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g., Assistant Professor, HOD", max_length=100
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="e.g., Ph.D. in Computer Science, M.Tech"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(help_text="Area of expertise", max_length=200),
                ),
                ("joining_date", models.DateField()),
                (
                    "office_hours",
                    models.CharField(
                        blank=True, help_text="e.g., Mon-Wed 2-4 PM", max_length=200
                    ),
                ),
                (
                    "teaching_load",
                    models.PositiveIntegerField(default=0, help_text="Hours per week"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculties",
                        to="core.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joining_date"],
                "indexes": [
                    models.Index(
                        fields=["department", "is_active"],
                        name="profile_man_departm_9bc629_idx",
                    )
                ],
            },
        ),
    ]
