# Generated by Django 6.0.2 on 2026-03-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_management", "0004_facultyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facultyprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
