# Generated by Django 6.0.2 on 2026-04-28 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0004_idcardtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='experience',
            field=models.CharField(blank=True, help_text="e.g., '15 Years'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='hod_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='research_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='FacultyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(help_text='Journal name or Conference name', max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('JOURNAL', 'Journal'), ('CONFERENCE', 'Conference'), ('BOOK_CHAPTER', 'Book Chapter')], max_length=20)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='profile_management.facultyprofile')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
