# Generated by Django 4.2.30 on 2026-04-21 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_add_section_priority"),
        (
            "profile_management",
            "0005_facultyprofile_first_name_facultyprofile_last_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionIncharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        limit_choices_to={"role__code": "FACULTY"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_charge_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_charge_history",
                        to="core.section",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_incharges",
                        to="profile_management.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section In-Charge",
                "verbose_name_plural": "Section In-Charges",
                "ordering": ["-semester__start_date", "section"],
                "indexes": [
                    models.Index(
                        fields=["section", "semester"],
                        name="profile_man_section_75d199_idx",
                    ),
                    models.Index(
                        fields=["faculty", "semester"],
                        name="profile_man_faculty_3c2626_idx",
                    ),
                ],
                "unique_together": {("section", "semester")},
            },
        ),
    ]
