# Generated by Django 4.2.30 on 2026-04-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_management", "0006_sectionincharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="faculty_profiles/"
            ),
        ),
    ]
