# Generated by Django 4.2.7 on 2026-04-26 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profile_management", "0001_initial"),
        ("core", "0002_school_remove_department_school_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Day"),
                            ("HALF_MORNING", "Half Day (Morning)"),
                            ("HALF_AFTERNOON", "Half Day (Afternoon)"),
                        ],
                        default="FULL",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_attachments/"
                    ),
                ),
                (
                    "substitution_note",
                    models.TextField(blank=True, help_text="Note about class handover"),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("hod_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="profile_management.facultyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("is_restricted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_paid", models.BooleanField(default=True)),
                ("allows_half_day", models.BooleanField(default=True)),
                ("allows_full_day", models.BooleanField(default=True)),
                (
                    "max_days_per_request",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "annual_quota",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("requires_attachment", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaveApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("remarks", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="leave_management.facultyleaverequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="facultyleaverequest",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="leave_management.leavetype",
            ),
        ),
        migrations.CreateModel(
            name="WeekendSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("is_weekend", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekend_settings",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "day")},
            },
        ),
        migrations.CreateModel(
            name="FacultyLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_granted",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "pending",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="profile_management.facultyprofile",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave_management.leavetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("faculty", "leave_type")},
            },
        ),
    ]
