# Generated by Django 4.2.7 on 2026-04-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyleaverequest",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
