# Generated by Django 6.0.2 on 2026-04-26 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_school_remove_department_school_name_and_more"),
        ("leave_management", "0002_facultyleaverequest_ai_summary"),
        ("profile_management", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant-Wide"),
                            ("school", "School-Wide"),
                            ("department", "Department"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "annual_quota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("carry_forward", models.BooleanField(blank=True, null=True)),
                (
                    "max_carry_forward",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("allows_half_day", models.BooleanField(blank=True, null=True)),
                ("requires_attachment", models.BooleanField(blank=True, null=True)),
                ("min_notice_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_consecutive_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="facultyleavebalance",
            name="year",
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddConstraint(
            model_name="facultyleaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="leave_management_valid_date_range",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_leave_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_policies",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="leave_management.leavetype",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_policies",
                to="core.school",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_policies",
                to="tenants.client",
            ),
        ),
        migrations.AddIndex(
            model_name="leavepolicy",
            index=models.Index(
                fields=["tenant", "leave_type", "is_active"],
                name="leave_manag_tenant__f0c957_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leavepolicy",
            index=models.Index(
                fields=["school", "leave_type", "is_active"],
                name="leave_manag_school__fb7b33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leavepolicy",
            index=models.Index(
                fields=["department", "leave_type", "is_active"],
                name="leave_manag_departm_401fe2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavepolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "tenant")),
                fields=("scope", "tenant", "leave_type", "effective_from"),
                name="leave_management_unique_tenant_policy_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavepolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "school")),
                fields=("scope", "school", "leave_type", "effective_from"),
                name="leave_management_unique_school_policy_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavepolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "department")),
                fields=("scope", "department", "leave_type", "effective_from"),
                name="leave_management_unique_dept_policy_date",
            ),
        ),
    ]
