# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('profile_management', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('INTERNAL', 'Internal Assessment'), ('EXTERNAL', 'External Exam'), ('QUIZ', 'Quiz'), ('LAB', 'Lab Exam'), ('ASSIGNMENT', 'Assignment')], default='INTERNAL', help_text='Type of examination', max_length=20)),
                ('exam_date', models.DateField(help_text='Date of the exam')),
                ('internal_max_mark', models.IntegerField(default=40, help_text='Maximum marks for internal assessment')),
                ('external_max_mark', models.IntegerField(default=60, help_text='Maximum marks for external exam')),
                ('pass_mark', models.IntegerField(default=40, help_text='Minimum marks required to pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Configuration',
                'verbose_name_plural': 'Exam Configurations',
            },
        ),
        migrations.CreateModel(
            name='CourseSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty member assigned to teach', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='profile_management.facultyprofile')),
                ('section', models.ForeignKey(help_text='Section being taught', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='core.section')),
                ('semester', models.ForeignKey(help_text='Academic semester', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='profile_management.semester')),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='timetable.subject')),
                ('exam_config', models.ForeignKey(help_text='Exam configuration for this course section', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='grades.examconfig')),
            ],
            options={
                'verbose_name': 'Course Section Assignment',
                'verbose_name_plural': 'Course Section Assignments',
            },
        ),
        migrations.CreateModel(
            name='GradeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current submission status', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When grades were submitted for approval', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When grades were approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='HOD/Admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grade_batches', to=settings.AUTH_USER_MODEL)),
                ('course_section_assignment', models.OneToOneField(help_text='Course section this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_batch', to='grades.coursesectionassignment')),
            ],
            options={
                'verbose_name': 'Grade Batch',
                'verbose_name_plural': 'Grade Batches',
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_mark', models.FloatField(blank=True, help_text='Internal assessment marks', null=True)),
                ('external_mark', models.FloatField(blank=True, help_text='External exam marks', null=True)),
                ('is_absent', models.BooleanField(default=False, help_text='Student was absent for the exam')),
                ('total_mark', models.FloatField(blank=True, help_text='Total marks (internal + external)', null=True)),
                ('percentage', models.FloatField(blank=True, help_text='Percentage scored', null=True)),
                ('letter_grade', models.CharField(blank=True, help_text='Letter grade (O, A+, A, B+, B, C, F, ABSENT, WITHHELD)', max_length=10)),
                ('grade_point', models.FloatField(blank=True, help_text='Grade point (0-10 scale)', null=True)),
                ('is_pass', models.BooleanField(help_text='Whether student passed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_batch', models.ForeignKey(help_text='Parent batch', on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='grades.gradebatch')),
                ('student', models.ForeignKey(help_text='Student receiving the grade', on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Grade Entry',
                'verbose_name_plural': 'Grade Entries',
            },
        ),
        migrations.CreateModel(
            name='SemesterGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, help_text='Semester GPA', max_digits=4)),
                ('total_credits', models.DecimalField(decimal_places=1, help_text='Total credits for the semester', max_digits=5)),
                ('credits_earned', models.DecimalField(decimal_places=1, help_text='Credits earned (passed courses)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(help_text='Academic semester', on_delete=django.db.models.deletion.CASCADE, related_name='semester_gpas', to='profile_management.semester')),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='semester_gpas', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Semester GPA',
                'verbose_name_plural': 'Semester GPAs',
                'ordering': ['-semester__start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentCGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Cumulative GPA', max_digits=4)),
                ('total_credits', models.DecimalField(decimal_places=1, help_text='Total credits across all semesters', max_digits=6)),
                ('credits_earned', models.DecimalField(decimal_places=1, help_text='Total credits earned (passed courses)', max_digits=6)),
                ('performance_trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], default='STABLE', help_text='Performance trend based on recent semesters', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='cgpa_record', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Student CGPA',
                'verbose_name_plural': 'Student CGPAs',
            },
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.DecimalField(decimal_places=2, default=0, help_text='Internal assessment marks (assignments, quizzes, etc.)', max_digits=5)),
                ('internal_max_marks', models.DecimalField(decimal_places=2, default=40, help_text='Maximum internal marks', max_digits=5)),
                ('exam_marks', models.DecimalField(decimal_places=2, default=0, help_text='Final exam marks', max_digits=5)),
                ('exam_max_marks', models.DecimalField(decimal_places=2, default=60, help_text='Maximum exam marks', max_digits=5)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm Exam'), ('FINAL', 'Final Exam'), ('BOTH', 'Midterm + Final')], default='FINAL', help_text='Type of exam', max_length=20)),
                ('exam_date', models.DateField(blank=True, help_text='Date of final exam', null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total marks obtained', max_digits=5)),
                ('total_max_marks', models.DecimalField(decimal_places=2, default=100, help_text='Total maximum marks', max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage scored', max_digits=5)),
                ('grade', models.CharField(choices=[('A+', 'A+ (90-100%)'), ('A', 'A (80-89%)'), ('B+', 'B+ (70-79%)'), ('B', 'B (60-69%)'), ('C', 'C (50-59%)'), ('D', 'D (40-49%)'), ('F', 'F (Below 40%)'), ('I', 'Incomplete'), ('W', 'Withdrawn')], help_text='Letter grade', max_length=2)),
                ('grade_points', models.DecimalField(decimal_places=2, help_text='Grade points (for GPA calculation)', max_digits=4)),
                ('credits', models.DecimalField(decimal_places=1, help_text='Course credits', max_digits=3)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or comments')),
                ('is_published', models.BooleanField(default=False, help_text='Whether grade is published to student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(help_text='Faculty who assigned the grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course_grades', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(help_text='Academic semester', on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='profile_management.semester')),
                ('student', models.ForeignKey(help_text='Student who received this grade', on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='profile_management.studentprofile')),
                ('subject', models.ForeignKey(help_text='Subject for which grade is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Course Grade',
                'verbose_name_plural': 'Course Grades',
                'ordering': ['-semester__start_date', 'subject__code'],
                'indexes': [models.Index(fields=['student', 'semester'], name='grades_cour_student_4bb4b9_idx'), models.Index(fields=['semester', 'is_published'], name='grades_cour_semeste_1ad8c8_idx')],
                'unique_together': {('student', 'subject', 'semester')},
            },
        ),
        migrations.AddIndex(
            model_name='coursesectionassignment',
            index=models.Index(fields=['faculty', 'semester'], name='grades_cour_faculty_1cab94_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesectionassignment',
            index=models.Index(fields=['section', 'semester'], name='grades_cour_section_bdf71e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesectionassignment',
            unique_together={('faculty', 'subject', 'section', 'semester')},
        ),
        migrations.AddIndex(
            model_name='gradebatch',
            index=models.Index(fields=['status', 'submitted_at'], name='grades_grad_status_4fe870_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['grade_batch', 'student'], name='grades_grad_grade_b_e7edfb_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['letter_grade'], name='grades_grad_letter__8ab858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeentry',
            unique_together={('grade_batch', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='semestergpa',
            unique_together={('student', 'semester')},
        ),
    ]
