# Generated by Django 5.0.2 on 2026-02-15 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile_management", "0003_studentprofile_current_gpa"),
        ("timetable", "0003_subject_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCGPA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        decimal_places=2, help_text="Cumulative GPA", max_digits=4
                    ),
                ),
                (
                    "total_credits",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total credits across all semesters",
                        max_digits=6,
                    ),
                ),
                (
                    "credits_earned",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total credits earned (passed courses)",
                        max_digits=6,
                    ),
                ),
                (
                    "performance_trend",
                    models.CharField(
                        choices=[
                            ("IMPROVING", "Improving"),
                            ("STABLE", "Stable"),
                            ("DECLINING", "Declining"),
                        ],
                        default="STABLE",
                        help_text="Performance trend based on recent semesters",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        help_text="Student",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cgpa_record",
                        to="profile_management.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student CGPA",
                "verbose_name_plural": "Student CGPAs",
            },
        ),
        migrations.CreateModel(
            name="CourseGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Internal assessment marks (assignments, quizzes, etc.)",
                        max_digits=5,
                    ),
                ),
                (
                    "internal_max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        help_text="Maximum internal marks",
                        max_digits=5,
                    ),
                ),
                (
                    "exam_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Final exam marks",
                        max_digits=5,
                    ),
                ),
                (
                    "exam_max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        help_text="Maximum exam marks",
                        max_digits=5,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("MIDTERM", "Midterm Exam"),
                            ("FINAL", "Final Exam"),
                            ("BOTH", "Midterm + Final"),
                        ],
                        default="FINAL",
                        help_text="Type of exam",
                        max_length=20,
                    ),
                ),
                (
                    "exam_date",
                    models.DateField(
                        blank=True, help_text="Date of final exam", null=True
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2, help_text="Total marks obtained", max_digits=5
                    ),
                ),
                (
                    "total_max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Total maximum marks",
                        max_digits=5,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="Percentage scored", max_digits=5
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A+", "A+ (90-100%)"),
                            ("A", "A (80-89%)"),
                            ("B+", "B+ (70-79%)"),
                            ("B", "B (60-69%)"),
                            ("C", "C (50-59%)"),
                            ("D", "D (40-49%)"),
                            ("F", "F (Below 40%)"),
                            ("I", "Incomplete"),
                            ("W", "Withdrawn"),
                        ],
                        help_text="Letter grade",
                        max_length=2,
                    ),
                ),
                (
                    "grade_points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade points (for GPA calculation)",
                        max_digits=4,
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(
                        decimal_places=1, help_text="Course credits", max_digits=3
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks or comments"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether grade is published to student"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        help_text="Faculty who assigned the grade",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_course_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Academic semester",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grades",
                        to="profile_management.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who received this grade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grades",
                        to="profile_management.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject for which grade is assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grades",
                        to="timetable.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Grade",
                "verbose_name_plural": "Course Grades",
                "ordering": ["-semester__start_date", "subject__code"],
                "indexes": [
                    models.Index(
                        fields=["student", "semester"],
                        name="grades_cour_student_4bb4b9_idx",
                    ),
                    models.Index(
                        fields=["semester", "is_published"],
                        name="grades_cour_semeste_1ad8c8_idx",
                    ),
                ],
                "unique_together": {("student", "subject", "semester")},
            },
        ),
        migrations.CreateModel(
            name="SemesterGPA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2, help_text="Semester GPA", max_digits=4
                    ),
                ),
                (
                    "total_credits",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total credits for the semester",
                        max_digits=5,
                    ),
                ),
                (
                    "credits_earned",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Credits earned (passed courses)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Academic semester",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_gpas",
                        to="profile_management.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_gpas",
                        to="profile_management.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester GPA",
                "verbose_name_plural": "Semester GPAs",
                "ordering": ["-semester__start_date"],
                "unique_together": {("student", "semester")},
            },
        ),
    ]
