# Generated by Django 6.0.2 on 2026-03-02 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tokenblacklist'),
        ('grades', '0001_initial'),
        ('profile_management', '0005_facultyprofile_first_name_facultyprofile_last_name'),
        ('timetable', '0003_subject_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('INTERNAL', 'Internal Assessment'), ('EXTERNAL', 'External Exam'), ('QUIZ', 'Quiz'), ('LAB', 'Lab Exam'), ('ASSIGNMENT', 'Assignment')], default='INTERNAL', help_text='Type of examination', max_length=20)),
                ('exam_date', models.DateField(help_text='Date of the exam')),
                ('internal_max_mark', models.IntegerField(default=40, help_text='Maximum marks for internal assessment')),
                ('external_max_mark', models.IntegerField(default=60, help_text='Maximum marks for external exam')),
                ('pass_mark', models.IntegerField(default=40, help_text='Minimum marks required to pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Configuration',
                'verbose_name_plural': 'Exam Configurations',
            },
        ),
        migrations.CreateModel(
            name='CourseSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty member assigned to teach', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='profile_management.facultyprofile')),
                ('section', models.ForeignKey(help_text='Section being taught', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='core.section')),
                ('semester', models.ForeignKey(help_text='Academic semester', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='profile_management.semester')),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='timetable.subject')),
                ('exam_config', models.ForeignKey(help_text='Exam configuration for this course section', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='grades.examconfig')),
            ],
            options={
                'verbose_name': 'Course Section Assignment',
                'verbose_name_plural': 'Course Section Assignments',
            },
        ),
        migrations.CreateModel(
            name='GradeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current submission status', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When grades were submitted for approval', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When grades were approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='HOD/Admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grade_batches', to=settings.AUTH_USER_MODEL)),
                ('course_section_assignment', models.OneToOneField(help_text='Course section this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_batch', to='grades.coursesectionassignment')),
            ],
            options={
                'verbose_name': 'Grade Batch',
                'verbose_name_plural': 'Grade Batches',
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_mark', models.FloatField(blank=True, help_text='Internal assessment marks', null=True)),
                ('external_mark', models.FloatField(blank=True, help_text='External exam marks', null=True)),
                ('is_absent', models.BooleanField(default=False, help_text='Student was absent for the exam')),
                ('total_mark', models.FloatField(blank=True, help_text='Total marks (internal + external)', null=True)),
                ('percentage', models.FloatField(blank=True, help_text='Percentage scored', null=True)),
                ('letter_grade', models.CharField(blank=True, help_text='Letter grade (O, A+, A, B+, B, C, F, ABSENT, WITHHELD)', max_length=10)),
                ('grade_point', models.FloatField(blank=True, help_text='Grade point (0-10 scale)', null=True)),
                ('is_pass', models.BooleanField(help_text='Whether student passed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_batch', models.ForeignKey(help_text='Parent batch', on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='grades.gradebatch')),
                ('student', models.ForeignKey(help_text='Student receiving the grade', on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Grade Entry',
                'verbose_name_plural': 'Grade Entries',
            },
        ),
        migrations.AddIndex(
            model_name='coursesectionassignment',
            index=models.Index(fields=['faculty', 'semester'], name='grades_cour_faculty_1cab94_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesectionassignment',
            index=models.Index(fields=['section', 'semester'], name='grades_cour_section_bdf71e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesectionassignment',
            unique_together={('faculty', 'subject', 'section', 'semester')},
        ),
        migrations.AddIndex(
            model_name='gradebatch',
            index=models.Index(fields=['status', 'submitted_at'], name='grades_grad_status_4fe870_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['grade_batch', 'student'], name='grades_grad_grade_b_e7edfb_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['letter_grade'], name='grades_grad_letter__8ab858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeentry',
            unique_together={('grade_batch', 'student')},
        ),
    ]
