# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('profile_management', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g., 'End Semester Exam - Fall 2026'", max_length=200)),
                ('exam_type', models.CharField(choices=[('MIDTERM_1', 'Midterm 1'), ('MIDTERM_2', 'Midterm 2'), ('MIDTERM_3', 'Midterm 3'), ('END_SEMESTER', 'End Semester'), ('SUPPLEMENTARY', 'Supplementary'), ('RE_EXAM', 'Re-Examination')], help_text='Type of examination', max_length=20)),
                ('start_date', models.DateField(help_text='First exam date')),
                ('end_date', models.DateField(help_text='Last exam date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current exam cycle status', max_length=20)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, help_text='Default maximum marks for exams in this cycle', max_digits=5)),
                ('pass_marks_percentage', models.DecimalField(decimal_places=2, default=40, help_text='Pass marks percentage', max_digits=5)),
                ('instructions', models.TextField(blank=True, help_text='General instructions for students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin/HOD who created this exam cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department (null = college-wide exam)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.department')),
                ('semester', models.ForeignKey(help_text='Academic semester this exam belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Exam date')),
                ('start_time', models.TimeField(help_text='Exam start time')),
                ('end_time', models.TimeField(help_text='Exam end time')),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (FN)'), ('AFTERNOON', 'Afternoon (AN)')], default='MORNING', help_text='Morning or afternoon shift', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=180, help_text='Exam duration in minutes')),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Override max marks (uses exam default if null)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this exam schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(help_text='Parent exam cycle', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam')),
                ('invigilator', models.ForeignKey(blank=True, help_text='Primary invigilator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Room allocated for this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='timetable.room')),
                ('section', models.ForeignKey(help_text='Section taking this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.section')),
                ('subject', models.ForeignKey(help_text='Subject being examined', on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENTERED', 'Entered'), ('VERIFIED', 'Verified'), ('PUBLISHED', 'Published'), ('WITHHELD', 'Withheld')], default='PENDING', help_text='Result status', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage scored', max_digits=5, null=True)),
                ('is_pass', models.BooleanField(default=False, help_text='Whether student passed')),
                ('is_absent', models.BooleanField(default=False, help_text='Whether student was absent')),
                ('remarks', models.TextField(blank=True, help_text='Remarks (malpractice, medical, etc.)')),
                ('published_at', models.DateTimeField(blank=True, help_text='When result was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(help_text='Faculty who entered marks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_exam_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='profile_management.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, help_text='HOD/admin who verified marks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_exam_results', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(help_text='Exam schedule', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examschedule')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['student__register_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSeatingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text="Seat/bench number, e.g., 'A-14', 'Row3-Seat5'", max_length=20)),
                ('is_present', models.BooleanField(default=False, help_text='Whether student was present for exam')),
                ('marked_at', models.DateTimeField(blank=True, help_text='When attendance was marked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, help_text='Room for this student (can differ from schedule room)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_seats', to='timetable.room')),
                ('schedule', models.ForeignKey(help_text='Exam schedule', on_delete=django.db.models.deletion.CASCADE, related_name='seating_arrangements', to='exams.examschedule')),
                ('student', models.ForeignKey(help_text='Student assigned to this seat', on_delete=django.db.models.deletion.CASCADE, related_name='exam_seats', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Seating Arrangement',
                'verbose_name_plural': 'Seating Arrangements',
                'ordering': ['room__room_number', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Unique hall ticket number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('DOWNLOADED', 'Downloaded'), ('REVOKED', 'Revoked')], default='GENERATED', max_length=20)),
                ('is_eligible', models.BooleanField(default=True, help_text='Whether student is eligible to appear')),
                ('ineligibility_reason', models.TextField(blank=True, help_text='Reason if not eligible (attendance shortage, fees due, etc.)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(help_text='Exam cycle', on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='exams.exam')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_hall_tickets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Hall Ticket',
                'verbose_name_plural': 'Hall Tickets',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['semester', 'exam_type'], name='exams_exam_semeste_5e87de_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'start_date'], name='exams_exam_status_ab8e48_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['department', 'semester'], name='exams_exam_departm_f4551a_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['exam', 'date'], name='exams_exams_exam_id_fd186a_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['subject', 'date'], name='exams_exams_subject_78a525_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['room', 'date', 'start_time'], name='exams_exams_room_id_3ac6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['section', 'date'], name='exams_exams_section_39be23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam', 'subject', 'section')},
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'status'], name='exams_examr_student_cbc162_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['schedule', 'status'], name='exams_examr_schedul_c65ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['status', 'is_pass'], name='exams_examr_status_942c5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('schedule', 'student')},
        ),
        migrations.AddIndex(
            model_name='examseatingarrangement',
            index=models.Index(fields=['student', 'schedule'], name='exams_exams_student_559be2_idx'),
        ),
        migrations.AddIndex(
            model_name='examseatingarrangement',
            index=models.Index(fields=['schedule', 'room'], name='exams_exams_schedul_5de230_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examseatingarrangement',
            unique_together={('schedule', 'room', 'seat_number'), ('schedule', 'student')},
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['student', 'exam'], name='exams_hallt_student_e4a532_idx'),
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['ticket_number'], name='exams_hallt_ticket__77c858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hallticket',
            unique_together={('student', 'exam')},
        ),
    ]
