TASK_ENTITY_STUDENT = "STUDENT"
TASK_ENTITY_FACULTY = "FACULTY"

TASK_ENTITY_CHOICES = [
    (TASK_ENTITY_STUDENT, "Student"),
    (TASK_ENTITY_FACULTY, "Faculty"),
]

TASK_STATUS_PENDING = "PENDING"
TASK_STATUS_PROCESSING = "PROCESSING"
TASK_STATUS_PARTIAL = "PARTIAL"
TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_FAILED = "FAILED"

TASK_STATUS_CHOICES = [
    (TASK_STATUS_PENDING, "Pending"),
    (TASK_STATUS_PROCESSING, "Processing"),
    (TASK_STATUS_PARTIAL, "Partial"),
    (TASK_STATUS_COMPLETED, "Completed"),
    (TASK_STATUS_FAILED, "Failed"),
]

ID_CARD_STATUS_PENDING = "PENDING"
ID_CARD_STATUS_READY = "READY"
ID_CARD_STATUS_ISSUED = "ISSUED"
ID_CARD_STATUS_REVOKED = "REVOKED"

ID_CARD_STATUS_CHOICES = [
    (ID_CARD_STATUS_PENDING, "Pending"),
    (ID_CARD_STATUS_READY, "Ready"),
    (ID_CARD_STATUS_ISSUED, "Issued"),
    (ID_CARD_STATUS_REVOKED, "Revoked"),
]

MAX_BULK_UPLOAD_FILE_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB
VALID_UPLOAD_EXTENSIONS = {".csv", ".xlsx"}
DEFAULT_CHUNK_SIZE = 100
MIN_CHUNK_SIZE = 50
MAX_CHUNK_SIZE = 100

ERROR_TYPE_VALIDATION = "VALIDATION_ERROR"
ERROR_TYPE_DB = "DB_ERROR"
ERROR_TYPE_SYSTEM = "SYSTEM_ERROR"

ONBOARDING_EVENT_STUDENT_CREATED = "STUDENT_CREATED"
ONBOARDING_EVENT_FACULTY_CREATED = "FACULTY_CREATED"
ONBOARDING_EVENT_ID_CARD_GENERATED = "ID_CARD_GENERATED"

ID_CARD_QR_TTL_SECONDS = 60 * 60 * 24 * 30  # 30 days
