"""
Django settings for CMS project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import importlib
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# AI Integration Settings
AI_SERVICE_BASE_URL = os.getenv('AI_SERVICE_BASE_URL', '').rstrip('/')
AI_SERVICE_API_SECRET = os.getenv('AI_SERVICE_API_SECRET', '')
AI_SERVICE_SOURCE_HEADER = os.getenv('AI_SERVICE_SOURCE_HEADER', 'django-cms-backend')
AI_SERVICE_CONNECT_TIMEOUT_SECONDS = int(os.getenv('AI_SERVICE_CONNECT_TIMEOUT_SECONDS', '5'))
AI_SERVICE_TIMEOUT_SECONDS = int(os.getenv('AI_SERVICE_TIMEOUT_SECONDS', '20'))
AI_SERVICE_INGEST_PATH = os.getenv('AI_SERVICE_INGEST_PATH', '/ingest')
AI_SERVICE_QUERY_PATH = os.getenv('AI_SERVICE_QUERY_PATH', '/query')
AI_SERVICE_DELETE_PATH = os.getenv('AI_SERVICE_DELETE_PATH', '/delete')

# Timetable AI Copilot — same FastAPI service, dedicated path prefix
TIMETABLE_AI_BASE_URL = os.getenv('TIMETABLE_AI_BASE_URL', 'http://localhost:8001')
TIMETABLE_AI_SECRET   = os.getenv('TIMETABLE_AI_SECRET', '1Nnzm1F7InKkjCPJmJopRMc9oX77ObVvyqKqMkz601j')


AI_INGEST_MAX_RETRIES = int(os.getenv('AI_INGEST_MAX_RETRIES', '3'))
AI_INGEST_BACKOFF_SECONDS = int(os.getenv('AI_INGEST_BACKOFF_SECONDS', '2'))

AI_CHAT_MAX_MESSAGE_LENGTH = int(os.getenv('AI_CHAT_MAX_MESSAGE_LENGTH', '1000'))
AI_CHAT_THROTTLE_RATE = os.getenv('AI_CHAT_THROTTLE_RATE', '20/hour')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3e((r7@i5fb(sj6fi4mw=f4*dazntggt+ov=ldh0q0_#(i$!7a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# ===========================================================================
# DJANGO-TENANTS CONFIGURATION
# ===========================================================================

# django-tenants model references
TENANT_MODEL = "tenants.Client"
TENANT_DOMAIN_MODEL = "tenants.Domain"

# Apps that live in the PUBLIC schema (shared across all tenants)
SHARED_APPS = [
    "django_tenants",
    "tenants",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",  # Core must be here so Admin can find the User model
    "corsheaders",
]

# Apps that live in each TENANT's private schema (data-isolated)
TENANT_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.admin",
    "django.contrib.sessions",
    "django.contrib.messages",
    "core",
    "profile_management",
    "timetable",
    "attendance",
    "assignment",
    "grades",
    "notifications",
    "configuration",
    "exams",
    "study_materials",
    "onboarding",
    "campus_management",
    "rest_framework",
    "strawberry.django",
]

# Combine: INSTALLED_APPS = SHARED_APPS + (TENANT_APPS not already in SHARED_APPS)
INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

try:
    importlib.import_module("django_q")
    from django.utils import baseconv  # noqa: F401
    INSTALLED_APPS.append("django_q")
except Exception:
    pass

# ===========================================================================
# DATABASE — django-tenants requires the postgresql_backend engine
# ===========================================================================

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("DB_NAME", "cms_db"),
        "USER": os.getenv("DB_USER", "cms_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "cms_password"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

DATABASE_ROUTERS = ["django_tenants.routers.TenantSyncRouter"]

# ===========================================================================
# MIDDLEWARE — TenantMainMiddleware MUST be first
# ===========================================================================

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.JWTAuthenticationMiddleware',  # Bearer token authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ===========================================================================
# URL CONFIGURATION
# ===========================================================================

ROOT_URLCONF = 'CMS.urls'
PUBLIC_SCHEMA_URLCONF = 'CMS.public_urls'

AUTH_USER_MODEL = "core.User"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CMS.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashing
# https://docs.djangoproject.com/en/6.0/topics/auth/passwords/
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# JWT Configuration
JWT_SECRET_KEY = SECRET_KEY  # Or use a separate secret
JWT_ALGORITHM = 'HS256'
JWT_ACCESS_TOKEN_LIFETIME = 24 * 60 * 60  # 24 hours in seconds
JWT_REFRESH_TOKEN_LIFETIME = 7 * 24 * 60 * 60  # 7 days in seconds

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://192.168.1.132:5174",
    "http://26.109.141.42:8000",
    "http://26.195.175.71:5174",
    "http://localhost:3000",
    "https://college-management-system-backend-64g7.onrender.com",
    "http://192.168.3.47:3000",
    "http://192.168.1.10:3000",
    "http://192.168.1.6:3000",
]

# Allow any subdomain of localhost on common frontend ports (3000, 5173, 5174)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://.*\.localhost:3000$",
    r"^http://.*\.localhost:5173$",
    r"^http://.*\.localhost:5174$",
]

CSRF_TRUSTED_ORIGINS = [
    "https://college-management-system-backend-64g7.onrender.com",
    "http://localhost:3000",
    "http://*.localhost:3000", # Support subdomains for CSRF as well
    "http://192.168.3.47:3000",
]

# If your frontend needs cookies/auth credentials, enable this:
# CORS_ALLOW_CREDENTIALS = True  
APPEND_SLASH = False

# Redis Configuration (for real-time notifications)
REDIS_URL = 'redis://localhost:6379/0'

# Notification Settings
NOTIFICATION_SSE_HEARTBEAT_INTERVAL = 30  # seconds
NOTIFICATION_SSE_MAX_CONNECTIONS_PER_USER = 3
NOTIFICATION_CLEANUP_DAYS = 90  # auto-delete notifications older than 90 days
NOTIFICATION_DEFAULT_EXPIRY_HOURS = 168  # 7 days for non-critical notifications

# Django REST Framework (for SSE endpoint)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.auth.JWTAuthentication',
        'notifications.sse.authentication.SSETokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'ai_chat': AI_CHAT_THROTTLE_RATE,
    },
}

Q_CLUSTER = {
    'name': 'cms_q_cluster',
    'workers': 2,
    'retry': 360,
    'timeout': 300,
    'max_attempts': 3,
    'ack_failures': True,
    'save_limit': 1000,
    'catch_up': False,
    'queue_limit': 500,
    'bulk': 10,
    'orm': 'default',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'ai_integration': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}