# Generated by Django 6.0.2 on 2026-02-08 09:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_studentprofile_course_and_more'),
        ('profile_management', '0002_academicyear_parentloginotp_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(help_text='Period number (1, 2, 3, ... 8)')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='Day of the week (1=Monday, 7=Sunday)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_definitions', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Period Definition',
                'verbose_name_plural': 'Period Definitions',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Room identifier (e.g., 301, Lab-A)', max_length=20, unique=True)),
                ('building', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of students')),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('SEMINAR', 'Seminar Hall'), ('AUDITORIUM', 'Auditorium')], default='CLASSROOM', max_length=20)),
                ('facilities', models.JSONField(default=dict, help_text='Available facilities: {"projector": true, "ac": true, etc.}')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department that primarily uses this room (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.department')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['building', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Subject code (e.g., CS301)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('semester_number', models.PositiveIntegerField(help_text='Which semester this subject is taught (1-8)')),
                ('credits', models.DecimalField(decimal_places=1, help_text='Credit hours for this subject', max_digits=3)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('ELECTIVE', 'Elective'), ('PROJECT', 'Project')], default='THEORY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['department', 'semester_number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TimetableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_day', models.PositiveIntegerField(default=8, help_text='Number of periods in a day')),
                ('default_period_duration', models.PositiveIntegerField(default=50, help_text='Default duration of each period in minutes')),
                ('day_start_time', models.TimeField(default=datetime.time(9, 30), help_text='When the academic day starts')),
                ('day_end_time', models.TimeField(default=datetime.time(16, 30), help_text='When the academic day ends')),
                ('lunch_break_after_period', models.PositiveIntegerField(default=4, help_text='After which period number the lunch break occurs')),
                ('lunch_break_duration', models.PositiveIntegerField(default=30, help_text='Lunch break duration in minutes')),
                ('short_break_duration', models.PositiveIntegerField(default=10, help_text='Short break duration between periods in minutes')),
                ('working_days', models.JSONField(default=list, help_text='List of working day numbers [1=Mon, 2=Tue, ..., 7=Sun]')),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_config', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Timetable Configuration',
                'verbose_name_plural': 'Timetable Configurations',
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty member teaching this class', limit_choices_to={'role__code': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedule', to=settings.AUTH_USER_MODEL)),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.perioddefinition')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='profile_management.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
            },
        ),
        migrations.AddIndex(
            model_name='perioddefinition',
            index=models.Index(fields=['semester', 'day_of_week'], name='timetable_p_semeste_e527f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='perioddefinition',
            unique_together={('semester', 'period_number', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['section', 'semester'], name='timetable_t_section_0007f9_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['faculty', 'semester'], name='timetable_t_faculty_95799d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['room', 'period_definition'], name='timetable_t_room_id_55de8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('section', 'period_definition', 'semester')},
        ),
    ]
