# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('profile_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField(unique=True)),
                ('is_break', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CombinedClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.IntegerField(blank=True, help_text='ID of ResourceAllocation from campus_management', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_combined_sessions', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, limit_choices_to={'role__code': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_teaching_schedule', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_class_sessions', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Combined Class Session',
                'verbose_name_plural': 'Combined Class Sessions',
            },
        ),
        migrations.CreateModel(
            name='CombinedClassSessionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='timetable.combinedclasssession')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_session_links', to='core.section')),
            ],
            options={
                'verbose_name': 'Combined Class Session Section',
                'verbose_name_plural': 'Combined Class Session Sections',
                'unique_together': {('combined_session', 'section')},
            },
        ),
        migrations.AddField(
            model_name='combinedclasssession',
            name='sections',
            field=models.ManyToManyField(related_name='combined_class_sessions', through='timetable.CombinedClassSessionSection', to='core.section'),
        ),
        migrations.CreateModel(
            name='DepartmentSectionCombinePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('max_sections', models.PositiveSmallIntegerField(default=2, help_text='Maximum number of sections allowed in a combined class for this department (1-2).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('same_course_only', models.BooleanField(default=True, help_text='If true, only sections from the same Course may be combined.')),
                ('allow_cross_department', models.BooleanField(default=False, help_text='If true, allows combining with explicitly allowed partner departments.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_partner_departments', models.ManyToManyField(blank=True, help_text='Departments this department is allowed to combine with (used only when allow_cross_department is true).', related_name='allowed_combine_partners', to='core.department')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_combine_policy', to='core.department')),
            ],
            options={
                'verbose_name': 'Department Section Combine Policy',
                'verbose_name_plural': 'Department Section Combine Policies',
            },
        ),
        migrations.CreateModel(
            name='PeriodDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(help_text='Period number (1, 2, 3, ... 8)')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='Day of the week (1=Monday, 7=Sunday)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_definitions', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Period Definition',
                'verbose_name_plural': 'Period Definitions',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='OverflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overflow_date', models.DateField(help_text='Calendar date on which the overflow occurred')),
                ('reason', models.CharField(choices=[('room_shortage', 'Room Shortage'), ('maintenance', 'Room Under Maintenance'), ('event', 'Room Occupied by Event')], default='room_shortage', max_length=100)),
                ('compensated', models.BooleanField(default=False, help_text='True once this section has been given compensatory priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_logs', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_logs', to='profile_management.semester')),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_logs', to='timetable.perioddefinition')),
            ],
            options={
                'verbose_name': 'Overflow Log',
                'verbose_name_plural': 'Overflow Logs',
            },
        ),
        migrations.CreateModel(
            name='NonRoomPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('LAB', 'Lab Practical'), ('PT', 'Physical Education'), ('LIBRARY', 'Library Period'), ('FREE', 'Free / Self-Study')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_room_periods', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_room_periods', to='profile_management.semester')),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_room_periods', to='timetable.perioddefinition')),
            ],
            options={
                'verbose_name': 'Non-Room Period',
                'verbose_name_plural': 'Non-Room Periods',
            },
        ),
        migrations.AddField(
            model_name='combinedclasssession',
            name='period_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_class_sessions', to='timetable.perioddefinition'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Room identifier (e.g., 301, Lab-A)', max_length=20, unique=True)),
                ('building', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of students')),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('SEMINAR', 'Seminar Hall'), ('AUDITORIUM', 'Auditorium')], default='CLASSROOM', max_length=20)),
                ('facilities', models.JSONField(default=dict, help_text='Available facilities: {"projector": true, "ac": true, etc.}')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department that primarily uses this room (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.department')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['building', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='LabRotationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='profile_management.semester')),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='timetable.perioddefinition')),
                ('lab', models.ForeignKey(limit_choices_to={'room_type': 'LAB'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='timetable.room')),
            ],
            options={
                'verbose_name': 'Lab Rotation Schedule',
                'verbose_name_plural': 'Lab Rotation Schedules',
            },
        ),
        migrations.AddField(
            model_name='combinedclasssession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_class_sessions', to='timetable.room'),
        ),
        migrations.CreateModel(
            name='RoomMaintenanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First date the room is under maintenance (inclusive)')),
                ('end_date', models.DateField(help_text='Last date the room is under maintenance (inclusive)')),
                ('reason', models.CharField(help_text='Short description of the maintenance reason', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to cancel/withdraw this maintenance block')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Room that will be unavailable', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_blocks', to='timetable.room')),
            ],
            options={
                'verbose_name': 'Room Maintenance Block',
                'verbose_name_plural': 'Room Maintenance Blocks',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Subject code (e.g., CS301)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Course description and objectives')),
                ('semester_number', models.PositiveIntegerField(help_text='Which semester this subject is taught (1-8)')),
                ('credits', models.DecimalField(decimal_places=1, help_text='Credit hours for this subject', max_digits=3)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TUTORIAL', 'Tutorial'), ('ELECTIVE', 'Elective'), ('PROJECT', 'Project')], default='THEORY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['department', 'semester_number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SectionSubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveIntegerField(default=1, help_text='Number of teaching periods required per week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty assigned to teach this subject to this section', limit_choices_to={'role__code': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='profile_management.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_requirements', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Section Subject Requirement',
                'verbose_name_plural': 'Section Subject Requirements',
                'ordering': ['section', 'subject'],
            },
        ),
        migrations.AddField(
            model_name='combinedclasssession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_class_sessions', to='timetable.subject'),
        ),
        migrations.CreateModel(
            name='TimetableApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_summary', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('slots', models.JSONField(blank=True, default=list, help_text='List of proposed timetable slots for UI rendering.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_approval_requests', to='core.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_timetable_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_approval_requests', to='profile_management.semester')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_timetable_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Approval Request',
                'verbose_name_plural': 'Timetable Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.IntegerField(blank=True, help_text='ID of ResourceAllocation from campus_management', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty member teaching this class', limit_choices_to={'role__code': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedule', to=settings.AUTH_USER_MODEL)),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.perioddefinition')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='profile_management.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_timetable_slots', to='core.section')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='profile_management.facultyprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='timetable.period')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ['class_section', 'day', 'period__order'],
            },
        ),
        migrations.CreateModel(
            name='AIActionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for this AI action batch (returned to the UI).', unique=True)),
                ('snapshot_data', models.JSONField(help_text='List of {entry_id, section_id, subject_id, faculty_id, period_definition_id, room_id, allocation_id, notes} dicts — one per affected TimetableEntry.')),
                ('constraints_applied', models.JSONField(help_text='The constraint list that was submitted (for audit / display).')),
                ('reverted', models.BooleanField(default=False, help_text='True once the admin has undone this action.')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_snapshots', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'AI Action Snapshot',
                'verbose_name_plural': 'AI Action Snapshots',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['semester', 'applied_at'], name='timetable_a_semeste_53a5ed_idx'), models.Index(fields=['reverted', 'applied_at'], name='timetable_a_reverte_d9c041_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='perioddefinition',
            index=models.Index(fields=['semester', 'day_of_week'], name='timetable_p_semeste_e527f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='perioddefinition',
            unique_together={('semester', 'period_number', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='overflowlog',
            index=models.Index(fields=['section', 'semester'], name='timetable_o_section_ae6e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='overflowlog',
            index=models.Index(fields=['semester', 'overflow_date'], name='timetable_o_semeste_721bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='overflowlog',
            index=models.Index(fields=['compensated'], name='timetable_o_compens_4f8446_idx'),
        ),
        migrations.AddIndex(
            model_name='nonroomperiod',
            index=models.Index(fields=['semester', 'period_definition'], name='timetable_n_semeste_478d27_idx'),
        ),
        migrations.AddIndex(
            model_name='nonroomperiod',
            index=models.Index(fields=['section', 'semester'], name='timetable_n_section_2bc927_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nonroomperiod',
            unique_together={('section', 'period_definition', 'semester')},
        ),
        migrations.AddIndex(
            model_name='labrotationschedule',
            index=models.Index(fields=['lab', 'period_definition', 'semester'], name='timetable_l_lab_id_54ef9e_idx'),
        ),
        migrations.AddIndex(
            model_name='labrotationschedule',
            index=models.Index(fields=['semester', 'is_active'], name='timetable_l_semeste_a9906b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labrotationschedule',
            unique_together={('section', 'semester')},
        ),
        migrations.AddIndex(
            model_name='roommaintenanceblock',
            index=models.Index(fields=['room', 'start_date', 'end_date'], name='timetable_r_room_id_b5952a_idx'),
        ),
        migrations.AddIndex(
            model_name='roommaintenanceblock',
            index=models.Index(fields=['is_active', 'start_date'], name='timetable_r_is_acti_81b6e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionsubjectrequirement',
            unique_together={('section', 'semester', 'subject')},
        ),
        migrations.AddIndex(
            model_name='combinedclasssession',
            index=models.Index(fields=['semester', 'period_definition'], name='timetable_c_semeste_3e3e21_idx'),
        ),
        migrations.AddIndex(
            model_name='combinedclasssession',
            index=models.Index(fields=['faculty', 'semester'], name='timetable_c_faculty_57d4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='combinedclasssession',
            index=models.Index(fields=['room', 'period_definition'], name='timetable_c_room_id_ab0efe_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableapprovalrequest',
            index=models.Index(fields=['department', 'status'], name='timetable_t_departm_c2b63c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableapprovalrequest',
            index=models.Index(fields=['semester', 'status'], name='timetable_t_semeste_406c01_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableapprovalrequest',
            index=models.Index(fields=['submitted_by', 'status'], name='timetable_t_submitt_38a925_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['section', 'semester'], name='timetable_t_section_0007f9_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['faculty', 'semester'], name='timetable_t_faculty_95799d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['room', 'period_definition'], name='timetable_t_room_id_55de8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('section', 'period_definition', 'semester')},
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['class_section', 'day'], name='timetable_t_class_s_8d7544_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['subject', 'faculty'], name='timetable_t_subject_74c21c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('class_section', 'day', 'period')},
        ),
    ]
