# Generated by Django 5.0.2 on 2026-02-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("THEORY", "Theory"),
                    ("LAB", "Lab"),
                    ("TUTORIAL", "Tutorial"),
                    ("ELECTIVE", "Elective"),
                    ("PROJECT", "Project"),
                ],
                default="THEORY",
                max_length=20,
            ),
        ),
    ]
