# Generated by Django 6.0.2 on 2026-04-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_remove_department_school_name_and_more'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. "2025-26"', max_length=20)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_grids', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_grids', to='core.department')),
            ],
            options={
                'verbose_name': 'Timetable Grid',
                'verbose_name_plural': 'Timetable Grids',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(help_text='1, 2, 3...')),
                ('slot_type', models.CharField(choices=[('class', 'Class'), ('lunch', 'Lunch'), ('break', 'Break'), ('free', 'Free')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(help_text='e.g. "Period 1", "Lunch Break"', max_length=50)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetablegrid')),
            ],
            options={
                'verbose_name': 'Period Slot',
                'verbose_name_plural': 'Period Slots',
                'ordering': ['grid', 'slot_number'],
                'unique_together': {('grid', 'slot_number')},
            },
        ),
    ]
