# Generated by Django 5.0.2 on 2026-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_alter_subject_subject_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True, help_text="Course description and objectives"
            ),
        ),
    ]
