# Generated by Django 6.0.2 on 2026-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0003_subject_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="allocation_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of ResourceAllocation from campus_management",
                null=True,
            ),
        ),
    ]
