# Generated by Django 6.0.2 on 2026-03-27 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_timetableentry_allocation_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimetableConfiguration",
        ),
    ]
