# Generated by Django 6.0.2 on 2026-04-19 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_section_priority'),
        ('profile_management', '0005_facultyprofile_first_name_facultyprofile_last_name'),
        ('timetable', '0005_delete_timetableconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRotationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(limit_choices_to={'room_type': 'LAB'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='timetable.room')),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='timetable.perioddefinition')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_rotations', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Lab Rotation Schedule',
                'verbose_name_plural': 'Lab Rotation Schedules',
                'indexes': [models.Index(fields=['lab', 'period_definition', 'semester'], name='timetable_l_lab_id_54ef9e_idx'), models.Index(fields=['semester', 'is_active'], name='timetable_l_semeste_a9906b_idx')],
                'unique_together': {('section', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='NonRoomPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('LAB', 'Lab Practical'), ('PT', 'Physical Education'), ('LIBRARY', 'Library Period'), ('FREE', 'Free / Self-Study')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_room_periods', to='timetable.perioddefinition')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_room_periods', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_room_periods', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Non-Room Period',
                'verbose_name_plural': 'Non-Room Periods',
                'indexes': [models.Index(fields=['semester', 'period_definition'], name='timetable_n_semeste_478d27_idx'), models.Index(fields=['section', 'semester'], name='timetable_n_section_2bc927_idx')],
                'unique_together': {('section', 'period_definition', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='OverflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overflow_date', models.DateField(help_text='Calendar date on which the overflow occurred')),
                ('reason', models.CharField(choices=[('room_shortage', 'Room Shortage'), ('maintenance', 'Room Under Maintenance'), ('event', 'Room Occupied by Event')], default='room_shortage', max_length=100)),
                ('compensated', models.BooleanField(default=False, help_text='True once this section has been given compensatory priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_logs', to='timetable.perioddefinition')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_logs', to='core.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_logs', to='profile_management.semester')),
            ],
            options={
                'verbose_name': 'Overflow Log',
                'verbose_name_plural': 'Overflow Logs',
                'indexes': [models.Index(fields=['section', 'semester'], name='timetable_o_section_ae6e7e_idx'), models.Index(fields=['semester', 'overflow_date'], name='timetable_o_semeste_721bcd_idx'), models.Index(fields=['compensated'], name='timetable_o_compens_4f8446_idx')],
            },
        ),
    ]
