# Generated by Django 5.0.2 on 2026-04-19 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_section_priority"),
        (
            "profile_management",
            "0005_facultyprofile_first_name_facultyprofile_last_name",
        ),
        ("timetable", "0006_add_scheduling_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomMaintenanceBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="First date the room is under maintenance (inclusive)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Last date the room is under maintenance (inclusive)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Short description of the maintenance reason",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to cancel/withdraw this maintenance block",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Room that will be unavailable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_blocks",
                        to="timetable.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Maintenance Block",
                "verbose_name_plural": "Room Maintenance Blocks",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["room", "start_date", "end_date"],
                        name="timetable_r_room_id_b5952a_idx",
                    ),
                    models.Index(
                        fields=["is_active", "start_date"],
                        name="timetable_r_is_acti_81b6e6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SectionSubjectRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periods_per_week",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of teaching periods required per week",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        help_text="Faculty assigned to teach this subject to this section",
                        limit_choices_to={"role__code": "FACULTY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_requirements",
                        to="core.section",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_requirements",
                        to="profile_management.semester",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_requirements",
                        to="timetable.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Subject Requirement",
                "verbose_name_plural": "Section Subject Requirements",
                "ordering": ["section", "subject"],
                "unique_together": {("section", "semester", "subject")},
            },
        ),
    ]
