# Generated by Django 5.0.2 on 2026-04-19

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0007_add_subject_requirement_and_maintenance_block"),
        ("core", "0007_add_section_priority"),
        (
            "profile_management",
            "0005_facultyprofile_first_name_facultyprofile_last_name",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentSectionCombinePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "max_sections",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Maximum number of sections allowed in a combined class for this department (1-2).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "same_course_only",
                    models.BooleanField(
                        default=True,
                        help_text="If true, only sections from the same Course may be combined.",
                    ),
                ),
                (
                    "allow_cross_department",
                    models.BooleanField(
                        default=False,
                        help_text="If true, allows combining with explicitly allowed partner departments.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_partner_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Departments this department is allowed to combine with (used only when allow_cross_department is true).",
                        related_name="allowed_combine_partners",
                        to="core.department",
                    ),
                ),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_combine_policy",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Section Combine Policy",
                "verbose_name_plural": "Department Section Combine Policies",
            },
        ),
        migrations.CreateModel(
            name="CombinedClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of ResourceAllocation from campus_management",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_combined_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        help_text=None,
                        limit_choices_to={"role__code": "FACULTY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combined_teaching_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combined_class_sessions",
                        to="timetable.perioddefinition",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combined_class_sessions",
                        to="timetable.room",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combined_class_sessions",
                        to="profile_management.semester",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combined_class_sessions",
                        to="timetable.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combined Class Session",
                "verbose_name_plural": "Combined Class Sessions",
            },
        ),
        migrations.CreateModel(
            name="CombinedClassSessionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combined_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_links",
                        to="timetable.combinedclasssession",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combined_session_links",
                        to="core.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combined Class Session Section",
                "verbose_name_plural": "Combined Class Session Sections",
                "unique_together": {("combined_session", "section")},
            },
        ),
        migrations.AddField(
            model_name="combinedclasssession",
            name="sections",
            field=models.ManyToManyField(
                related_name="combined_class_sessions",
                through="timetable.CombinedClassSessionSection",
                to="core.section",
            ),
        ),
        migrations.AddIndex(
            model_name="combinedclasssession",
            index=models.Index(fields=["semester", "period_definition"], name="timetable_co_semeste_5bbd10_idx"),
        ),
        migrations.AddIndex(
            model_name="combinedclasssession",
            index=models.Index(fields=["faculty", "semester"], name="timetable_co_faculty_017ef6_idx"),
        ),
        migrations.AddIndex(
            model_name="combinedclasssession",
            index=models.Index(fields=["room", "period_definition"], name="timetable_co_room_7a0ab9_idx"),
        ),
    ]
