# Generated by Django 6.0.2 on 2026-04-19 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_add_section_combining_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='combinedclasssession',
            new_name='timetable_c_semeste_3e3e21_idx',
            old_name='timetable_co_semeste_5bbd10_idx',
        ),
        migrations.RenameIndex(
            model_name='combinedclasssession',
            new_name='timetable_c_faculty_57d4d2_idx',
            old_name='timetable_co_faculty_017ef6_idx',
        ),
        migrations.RenameIndex(
            model_name='combinedclasssession',
            new_name='timetable_c_room_id_ab0efe_idx',
            old_name='timetable_co_room_7a0ab9_idx',
        ),
        migrations.AlterField(
            model_name='combinedclasssession',
            name='faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__code': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_teaching_schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
