# Generated by Django 5.0.2 on 2026-04-19 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profile_management",
            "0005_facultyprofile_first_name_facultyprofile_last_name",
        ),
        (
            "timetable",
            "0009_rename_timetable_co_semeste_5bbd10_idx_timetable_c_semeste_3e3e21_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AIActionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Stable identifier for this AI action batch (returned to the UI).",
                        unique=True,
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        help_text="List of {entry_id, section_id, subject_id, faculty_id, period_definition_id, room_id, allocation_id, notes} dicts — one per affected TimetableEntry."
                    ),
                ),
                (
                    "constraints_applied",
                    models.JSONField(
                        help_text="The constraint list that was submitted (for audit / display)."
                    ),
                ),
                (
                    "reverted",
                    models.BooleanField(
                        default=False,
                        help_text="True once the admin has undone this action.",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_action_snapshots",
                        to="profile_management.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Action Snapshot",
                "verbose_name_plural": "AI Action Snapshots",
                "ordering": ["-applied_at"],
                "indexes": [
                    models.Index(
                        fields=["semester", "applied_at"],
                        name="timetable_a_semeste_53a5ed_idx",
                    ),
                    models.Index(
                        fields=["reverted", "applied_at"],
                        name="timetable_a_reverte_d9c041_idx",
                    ),
                ],
            },
        ),
    ]
