# Generated by Django 6.0.2 on 2026-04-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_add_timetable_approval_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetableapprovalrequest',
            new_name='timetable_t_departm_c2b63c_idx',
            old_name='timetable_t_departm_8d9f08_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableapprovalrequest',
            new_name='timetable_t_semeste_406c01_idx',
            old_name='timetable_t_semeste_b1453e_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableapprovalrequest',
            new_name='timetable_t_submitt_38a925_idx',
            old_name='timetable_t_submitt_a2b7a2_idx',
        ),
    ]
