# Generated by Django 6.0.2 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_section_priority"),
        ("profile_management", "0005_facultyprofile_first_name_facultyprofile_last_name"),
        ("timetable", "0012_rename_timetable_t_departm_8d9f08_idx_timetable_t_departm_c2b63c_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=100, unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("order", models.PositiveIntegerField(unique=True)),
                ("is_break", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_section",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="hod_timetable_slots",
                        to="core.section",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="timetable_slots",
                        to="profile_management.facultyprofile",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="timetable.period",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="timetable_slots",
                        to="timetable.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Slot",
                "verbose_name_plural": "Timetable Slots",
                "ordering": ["class_section", "day", "period__order"],
                "indexes": [
                    models.Index(fields=["class_section", "day"], name="timetable_t_class_s_5dbb16_idx"),
                    models.Index(fields=["subject", "faculty"], name="timetable_t_subject_aefa2b_idx"),
                ],
                "unique_together": {("class_section", "day", "period")},
            },
        ),
    ]
