# Generated by Django 6.0.2 on 2026-04-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_add_hod_timetable_assignment_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetableslot',
            new_name='timetable_t_class_s_8d7544_idx',
            old_name='timetable_t_class_s_5dbb16_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableslot',
            new_name='timetable_t_subject_74c21c_idx',
            old_name='timetable_t_subject_aefa2b_idx',
        ),
    ]
