from django.urls import path

from .views import (
    FacultyCoursesView,
    FacultyDashboardView,
    HODFacultyListView,
    FacultyProfileView,
    FacultyStudentsView,
    ParentRequestOtpView,
    ParentVerifyOtpView,
    StudentAdminProfileUpdateView,
    StudentCourseOverviewView,
    StudentCoursesView,
    StudentDashboardView,
    StudentListView,
    StudentProfileDetailView,
    StudentProfilePhotoUpdateView,
    StudentIDCardPDFView,
    FacultyIDCardPDFView,
    BulkIDCardPDFView,
    IDCardTemplateView,
    IDCardTemplateResetView,
)

urlpatterns = [
    path("students/", StudentListView.as_view(), name="profile-students"),
    path("id-cards/bulk-generate/", BulkIDCardPDFView.as_view(), name="profile-bulk-id-card"),
    path("students/<str:register_number>/id-card/", StudentIDCardPDFView.as_view(), name="profile-student-id-card"),
    path("faculty/<int:faculty_id>/id-card/", FacultyIDCardPDFView.as_view(), name="profile-faculty-id-card"),
    path("students/<str:register_number>/", StudentProfileDetailView.as_view(), name="profile-student-detail"),
    path(
        "students/<str:register_number>/photo/",
        StudentProfilePhotoUpdateView.as_view(),
        name="profile-student-photo-update",
    ),
    path(
        "students/<str:register_number>/admin/",
        StudentAdminProfileUpdateView.as_view(),
        name="profile-student-admin-update",
    ),
    path(
        "students/<str:register_number>/dashboard/",
        StudentDashboardView.as_view(),
        name="profile-student-dashboard",
    ),
    path(
        "students/<str:register_number>/courses/",
        StudentCoursesView.as_view(),
        name="profile-student-courses",
    ),
    path(
        "students/<str:register_number>/courses/overview/",
        StudentCourseOverviewView.as_view(),
        name="profile-student-courses-overview",
    ),
    path("faculty/me/", FacultyProfileView.as_view(), name="profile-faculty-me"),
    path("faculty/dashboard/", FacultyDashboardView.as_view(), name="profile-faculty-dashboard"),
    path("faculty/courses/", FacultyCoursesView.as_view(), name="profile-faculty-courses"),
    path("faculty/students/", FacultyStudentsView.as_view(), name="profile-faculty-students"),
    path("hod/faculty-list/", HODFacultyListView.as_view(), name="profile-hod-faculty-list"),
    path("parents/request-otp/", ParentRequestOtpView.as_view(), name="profile-parent-request-otp"),
    path("parents/verify-otp/", ParentVerifyOtpView.as_view(), name="profile-parent-verify-otp"),
    path("id-card-template/", IDCardTemplateView.as_view(), name="profile-id-card-template"),
    path("id-card-template/reset/", IDCardTemplateResetView.as_view(), name="profile-id-card-template-reset"),
]
