# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
import onboarding.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('card_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('qr_token', models.TextField(blank=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=onboarding.models.id_card_qr_path)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=onboarding.models.id_card_pdf_path)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='profile_management.facultyprofile')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_faculty_id_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacultyOnboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('is_hod', models.BooleanField(default=False)),
                ('subject_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_record', to='profile_management.facultyprofile')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('card_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('qr_token', models.TextField(blank=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=onboarding.models.id_card_qr_path)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=onboarding.models.id_card_pdf_path)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_student_id_cards', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='profile_management.studentprofile')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentOnboardingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_onboarding_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_student_onboarding_approvals', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_approval', to='profile_management.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('entity_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty')], default='STUDENT', max_length=20)),
                ('entity_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'action', 'created_at'], name='onboarding__entity__539dee_idx'), models.Index(fields=['actor', 'created_at'], name='onboarding__actor_i_ea4fcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_onboarding_drafts', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_onboarding_drafts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_onboarding_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['entity_type', 'status', 'updated_at'], name='onboarding__entity__719318_idx'), models.Index(fields=['created_by', 'updated_at'], name='onboarding__created_33b03d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('entity_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty')], default='STUDENT', max_length=20)),
                ('file', models.FileField(upload_to=onboarding.models.onboarding_upload_file_path)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('is_retry', models.BooleanField(default=False)),
                ('retry_attempt', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration_ms', models.PositiveBigIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('failure_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_tasks', to='onboarding.onboardingtasklog')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_task_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'status'], name='onboarding__entity__a4db8e_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='onboarding__uploade_a6bf1d_idx'), models.Index(fields=['is_active', 'entity_type', 'created_at'], name='onboarding__is_acti_965efb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dry_run', False), ('is_active', True), ('is_retry', False)), fields=('entity_type', 'file_hash'), name='uq_onboarding_entity_filehash_active')],
            },
        ),
        migrations.CreateModel(
            name='TemporaryOnboardingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('can_bulk_upload', models.BooleanField(default=True)),
                ('can_retry', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_onboarding_accesses', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_onboarding_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['faculty_user', 'is_active', 'expires_at'], name='onboarding__faculty_034c0a_idx')],
            },
        ),
    ]
