# Generated by Django 6.0.2 on 2026-02-25 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE_SESSION_OPENED", "Attendance Session Opened"),
                            ("ATTENDANCE_SESSION_CLOSED", "Attendance Session Closed"),
                            ("LOW_ATTENDANCE_ALERT", "Low Attendance Alert"),
                            ("ATTENDANCE_MARKED", "Attendance Marked"),
                            ("ASSIGNMENT_PUBLISHED", "Assignment Published"),
                            ("ASSIGNMENT_DUE_SOON", "Assignment Due Soon"),
                            ("ASSIGNMENT_OVERDUE", "Assignment Overdue"),
                            ("ASSIGNMENT_GRADED", "Assignment Graded"),
                            ("ASSIGNMENT_RETURNED", "Assignment Returned"),
                            ("SUBMISSION_RECEIVED", "Submission Received"),
                            ("GRADE_PUBLISHED", "Grade Published"),
                            ("RESULT_DECLARED", "Result Declared"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("FEE_REMINDER", "Fee Reminder"),
                            ("SYSTEM_ALERT", "System Alert"),
                            ("PROFILE_UPDATE", "Profile Update"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE", "Attendance"),
                            ("ASSIGNMENT", "Assignment"),
                            ("GRADE", "Grade"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    ),
                    models.Index(
                        fields=["recipient", "category", "-created_at"],
                        name="notificatio_recipie_7b1202_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="notificatio_expires_4f3289_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE", "Attendance"),
                            ("ASSIGNMENT", "Assignment"),
                            ("GRADE", "Grade"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_sse_enabled", models.BooleanField(default=True)),
                ("is_email_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "unique_together": {("user", "category")},
            },
        ),
    ]
