# Generated by Django 6.0.2 on 2026-04-28 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_department_vision'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentNotice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('STUDENTS', 'Students'), ('FACULTY', 'Faculty'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_notices', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.department')),
            ],
            options={
                'verbose_name': 'Department Notice',
                'verbose_name_plural': 'Department Notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
