# Generated by Django 6.0.2 on 2026-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_departmentnotice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("ATTENDANCE", "Attendance"),
                    ("ASSIGNMENT", "Assignment"),
                    ("GRADE", "Grade"),
                    ("PLACEMENT", "Placement"),
                    ("SYSTEM", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ATTENDANCE_SESSION_OPENED", "Attendance Session Opened"),
                    ("ATTENDANCE_SESSION_CLOSED", "Attendance Session Closed"),
                    ("LOW_ATTENDANCE_ALERT", "Low Attendance Alert"),
                    ("ATTENDANCE_MARKED", "Attendance Marked"),
                    ("ASSIGNMENT_PUBLISHED", "Assignment Published"),
                    ("ASSIGNMENT_DUE_SOON", "Assignment Due Soon"),
                    ("ASSIGNMENT_OVERDUE", "Assignment Overdue"),
                    ("ASSIGNMENT_GRADED", "Assignment Graded"),
                    ("ASSIGNMENT_RETURNED", "Assignment Returned"),
                    ("SUBMISSION_RECEIVED", "Submission Received"),
                    ("GRADE_PUBLISHED", "Grade Published"),
                    ("RESULT_DECLARED", "Result Declared"),
                    (
                        "PLACEMENT_APPLICATION_CONFIRMED",
                        "Placement Application Confirmed",
                    ),
                    (
                        "PLACEMENT_APPLICATION_SHORTLISTED",
                        "Placement Application Shortlisted",
                    ),
                    (
                        "PLACEMENT_APPLICATION_SELECTED",
                        "Placement Application Selected",
                    ),
                    (
                        "PLACEMENT_APPLICATION_REJECTED",
                        "Placement Application Rejected",
                    ),
                    ("PLACEMENT_OFFER_UPLOADED", "Placement Offer Uploaded"),
                    ("ANNOUNCEMENT", "Announcement"),
                    ("FEE_REMINDER", "Fee Reminder"),
                    ("SYSTEM_ALERT", "System Alert"),
                    ("PROFILE_UPDATE", "Profile Update"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="category",
            field=models.CharField(
                choices=[
                    ("ATTENDANCE", "Attendance"),
                    ("ASSIGNMENT", "Assignment"),
                    ("GRADE", "Grade"),
                    ("PLACEMENT", "Placement"),
                    ("SYSTEM", "System"),
                ],
                max_length=20,
            ),
        ),
    ]
