# Generated by Django 6.0.2 on 2026-02-13 11:21

import assignment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tokenblacklist'),
        ('profile_management', '0002_academicyear_parentloginotp_semester'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description and instructions')),
                ('assignment_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('LAB', 'Lab Assignment'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz')], default='INDIVIDUAL', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Optional assignment file (PDF, DOC, etc.)', null=True, upload_to=assignment.models.assignment_file_path)),
                ('published_date', models.DateTimeField(blank=True, help_text='When assignment was published to students', null=True)),
                ('due_date', models.DateTimeField(help_text='Submission deadline')),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Allow submissions after due date')),
                ('late_submission_deadline', models.DateTimeField(blank=True, help_text='Final deadline for late submissions', null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this assignment', max_digits=6)),
                ('weightage', models.DecimalField(decimal_places=2, default=10.0, help_text='Weightage in final grade (percentage)', max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('GRADED', 'Graded')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Faculty who created this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(help_text='Section to which assignment is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.section')),
                ('semester', models.ForeignKey(help_text='Academic semester', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='profile_management.semester')),
                ('subject', models.ForeignKey(help_text='Subject for which assignment is created', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, help_text='Text submission or comments')),
                ('attachment', models.FileField(blank=True, help_text='Submitted file (PDF, DOC, ZIP, etc.)', null=True, upload_to=assignment.models.submission_file_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When submission was made')),
                ('is_late', models.BooleanField(default=False, help_text='Whether submission was after due date')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED', 'Returned'), ('RESUBMITTED', 'Resubmitted')], db_index=True, default='SUBMITTED', max_length=20)),
                ('graded_at', models.DateTimeField(blank=True, help_text='When submission was graded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='Assignment being submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignment.assignment')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Faculty who graded this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student submitting the assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks awarded to student', max_digits=6)),
                ('feedback', models.TextField(blank=True, help_text='Faculty feedback and comments')),
                ('grading_rubric', models.JSONField(blank=True, help_text='Detailed rubric breakdown (optional)', null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(help_text='Faculty who graded', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grades', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(help_text='Submission being graded', on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignment.assignmentsubmission')),
            ],
            options={
                'verbose_name': 'Assignment Grade',
                'verbose_name_plural': 'Assignment Grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'due_date'], name='assignment__status_ce6dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['subject', 'section'], name='assignment__subject_fac838_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='assignment__assignm_db117e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='assignment__student_22f6d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
