# Generated by Django 6.0.2 on 2026-04-21 19:21

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description and instructions')),
                ('assignment_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('LAB', 'Lab Assignment'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz')], default='INDIVIDUAL', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Optional assignment file (PDF, DOC, etc.)', null=True, upload_to=assignment.models.assignment_file_path)),
                ('published_date', models.DateTimeField(blank=True, help_text='When assignment was published to students', null=True)),
                ('due_date', models.DateTimeField(help_text='Submission deadline')),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Allow submissions after due date')),
                ('late_submission_deadline', models.DateTimeField(blank=True, help_text='Final deadline for late submissions', null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this assignment', max_digits=6)),
                ('weightage', models.DecimalField(decimal_places=2, default=10.0, help_text='Weightage in final grade (percentage)', max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('GRADED', 'Graded')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks awarded to student', max_digits=6)),
                ('feedback', models.TextField(blank=True, help_text='Faculty feedback and comments')),
                ('grading_rubric', models.JSONField(blank=True, help_text='Detailed rubric breakdown (optional)', null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment Grade',
                'verbose_name_plural': 'Assignment Grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, help_text='Text submission or comments')),
                ('attachment', models.FileField(blank=True, help_text='Submitted file (PDF, DOC, ZIP, etc.)', null=True, upload_to=assignment.models.submission_file_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When submission was made')),
                ('is_late', models.BooleanField(default=False, help_text='Whether submission was after due date')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED', 'Returned'), ('RESUBMITTED', 'Resubmitted')], db_index=True, default='SUBMITTED', max_length=20)),
                ('graded_at', models.DateTimeField(blank=True, help_text='When submission was graded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
