# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
        ('core', '0001_initial'),
        ('profile_management', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(help_text='Faculty who created this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(help_text='Section to which assignment is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.ForeignKey(help_text='Academic semester', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='profile_management.semester'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(help_text='Subject for which assignment is created', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='graded_by',
            field=models.ForeignKey(help_text='Faculty who graded', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(help_text='Assignment being submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignment.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, help_text='Faculty who graded this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(help_text='Student submitting the assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='profile_management.studentprofile'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='submission',
            field=models.OneToOneField(help_text='Submission being graded', on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignment.assignmentsubmission'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'due_date'], name='assignment__status_ce6dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['subject', 'section'], name='assignment__subject_fac838_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='assignment__assignm_db117e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='assignment__student_22f6d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
