# Generated by Django 6.0.2 on 2026-04-21 19:21

import attendance.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.PositiveIntegerField(default=0, help_text='Total number of classes held (excluding blocked/cancelled)')),
                ('present_count', models.PositiveIntegerField(default=0, help_text='Number of classes attended')),
                ('absent_count', models.PositiveIntegerField(default=0, help_text='Number of classes missed')),
                ('late_count', models.PositiveIntegerField(default=0, help_text='Number of times late')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of classes attended', max_digits=5)),
                ('is_below_threshold', models.BooleanField(db_index=True, default=False, help_text='True if attendance is below minimum required (usually 75%)')),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='When this report was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'db_table': 'attendance_report',
                'ordering': ['-attendance_percentage'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when this attendance session occurs')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When the session was opened', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the session was closed', null=True)),
                ('attendance_window_minutes', models.PositiveIntegerField(default=10, help_text='Minutes after session opens during which students can mark attendance')),
                ('cancellation_reason', models.CharField(blank=True, help_text="Reason for blocking/cancelling (e.g., 'Teacher sick', 'Holiday')", max_length=500)),
                ('blocked_at', models.DateTimeField(blank=True, help_text='When the session was blocked', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_session',
                'ordering': ['-date', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('punch_in_photo', models.ImageField(blank=True, null=True, upload_to=attendance.models.faculty_attendance_image_path)),
                ('punch_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out_photo', models.ImageField(blank=True, null=True, upload_to=attendance.models.faculty_attendance_image_path)),
                ('punch_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Attendance',
                'verbose_name_plural': 'Faculty Attendances',
                'db_table': 'faculty_attendance',
                'ordering': ['-date', '-punch_in_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], db_index=True, default='ABSENT', max_length=20)),
                ('attendance_image', models.ImageField(blank=True, help_text='Photo captured during attendance marking (required for present)', null=True, upload_to=attendance.models.attendance_image_path)),
                ('marked_at', models.DateTimeField(blank=True, help_text='When student marked attendance', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude where attendance was marked', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude where attendance was marked', max_digits=9, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device information (browser, OS, etc.)')),
                ('is_manually_marked', models.BooleanField(default=False, help_text='True if marked manually by faculty/admin (not by student)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., reason for late, manual marking reason)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendances',
                'db_table': 'student_attendance',
                'ordering': ['-session__date', 'student__first_name'],
            },
        ),
    ]
