# Generated by Django 6.0.2 on 2026-02-08 12:43

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_management', '0002_academicyear_parentloginotp_semester'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when this attendance session occurs')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When the session was opened', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the session was closed', null=True)),
                ('attendance_window_minutes', models.PositiveIntegerField(default=10, help_text='Minutes after session opens during which students can mark attendance')),
                ('cancellation_reason', models.CharField(blank=True, help_text="Reason for blocking/cancelling (e.g., 'Teacher sick', 'Holiday')", max_length=500)),
                ('blocked_at', models.DateTimeField(blank=True, help_text='When the session was blocked', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='Faculty/Admin who blocked this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(help_text='Faculty who opened this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
                ('timetable_entry', models.ForeignKey(help_text='The timetable entry (class) for which attendance is being taken', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='timetable.timetableentry')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_session',
                'ordering': ['-date', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], db_index=True, default='ABSENT', max_length=20)),
                ('attendance_image', models.ImageField(blank=True, help_text='Photo captured during attendance marking (required for present)', null=True, upload_to=attendance.models.attendance_image_path)),
                ('marked_at', models.DateTimeField(blank=True, help_text='When student marked attendance', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude where attendance was marked', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude where attendance was marked', max_digits=9, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device information (browser, OS, etc.)')),
                ('is_manually_marked', models.BooleanField(default=False, help_text='True if marked manually by faculty/admin (not by student)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., reason for late, manual marking reason)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Faculty/Admin who manually marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='profile_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendances',
                'db_table': 'student_attendance',
                'ordering': ['-session__date', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.PositiveIntegerField(default=0, help_text='Total number of classes held (excluding blocked/cancelled)')),
                ('present_count', models.PositiveIntegerField(default=0, help_text='Number of classes attended')),
                ('absent_count', models.PositiveIntegerField(default=0, help_text='Number of classes missed')),
                ('late_count', models.PositiveIntegerField(default=0, help_text='Number of times late')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of classes attended', max_digits=5)),
                ('is_below_threshold', models.BooleanField(db_index=True, default=False, help_text='True if attendance is below minimum required (usually 75%)')),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='When this report was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='profile_management.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='profile_management.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'db_table': 'attendance_report',
                'ordering': ['-attendance_percentage'],
                'indexes': [models.Index(fields=['student', 'semester'], name='attendance__student_672f72_idx'), models.Index(fields=['subject', 'semester'], name='attendance__subject_35ae39_idx'), models.Index(fields=['is_below_threshold'], name='attendance__is_belo_217029_idx'), models.Index(fields=['attendance_percentage'], name='attendance__attenda_cfec89_idx')],
                'unique_together': {('student', 'subject', 'semester')},
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date', 'status'], name='attendance__date_ed3ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['timetable_entry', 'date'], name='attendance__timetab_92b124_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'opened_at'], name='attendance__status_3fc1f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('timetable_entry', 'date')},
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['session', 'student'], name='student_att_session_6d6894_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'status'], name='student_att_student_494189_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['session', 'status'], name='student_att_session_6fd8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['marked_at'], name='student_att_marked__02b02f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('session', 'student')},
        ),
    ]
