# Generated by Django 5.0.2 on 2026-03-11 15:31

import attendance.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("punch_in_time", models.DateTimeField(blank=True, null=True)),
                (
                    "punch_in_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=attendance.models.faculty_attendance_image_path,
                    ),
                ),
                (
                    "punch_in_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "punch_in_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("punch_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "punch_out_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=attendance.models.faculty_attendance_image_path,
                    ),
                ),
                (
                    "punch_out_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "punch_out_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty Attendance",
                "verbose_name_plural": "Faculty Attendances",
                "db_table": "faculty_attendance",
                "ordering": ["-date", "-punch_in_time"],
                "indexes": [
                    models.Index(
                        fields=["faculty", "date"],
                        name="faculty_att_faculty_c9caa7_idx",
                    ),
                    models.Index(fields=["date"], name="faculty_att_date_d6960e_idx"),
                ],
                "unique_together": {("faculty", "date")},
            },
        ),
    ]
