# Generated by Django 6.0.2 on 2026-04-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('profile_management', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='profile_management.semester'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='profile_management.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='Faculty/Admin who blocked this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='combined_session',
            field=models.ForeignKey(blank=True, help_text='The combined class session for which attendance is being taken (if combined)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='timetable.combinedclasssession'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='opened_by',
            field=models.ForeignKey(help_text='Faculty who opened this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, help_text='The timetable entry (class) for which attendance is being taken (if not a combined class)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='timetable.timetableentry'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, help_text='Faculty/Admin who manually marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='profile_management.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['student', 'semester'], name='attendance__student_672f72_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['subject', 'semester'], name='attendance__subject_35ae39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['is_below_threshold'], name='attendance__is_belo_217029_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['attendance_percentage'], name='attendance__attenda_cfec89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancereport',
            unique_together={('student', 'subject', 'semester')},
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date', 'status'], name='attendance__date_ed3ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['timetable_entry', 'date'], name='attendance__timetab_92b124_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['combined_session', 'date'], name='attendance__combine_a3d6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'opened_at'], name='attendance__status_3fc1f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('timetable_entry__isnull', False), ('combined_session__isnull', True)), models.Q(('timetable_entry__isnull', True), ('combined_session__isnull', False)), _connector='OR'), name='attendance_session_exactly_one_class_ref'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('timetable_entry__isnull', False)), fields=('timetable_entry', 'date'), name='attendance_unique_timetable_entry_date'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('combined_session__isnull', False)), fields=('combined_session', 'date'), name='attendance_unique_combined_session_date'),
        ),
        migrations.AddIndex(
            model_name='facultyattendance',
            index=models.Index(fields=['faculty', 'date'], name='faculty_att_faculty_c9caa7_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyattendance',
            index=models.Index(fields=['date'], name='faculty_att_date_d6960e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facultyattendance',
            unique_together={('faculty', 'date')},
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['session', 'student'], name='student_att_session_6d6894_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'status'], name='student_att_student_494189_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['session', 'status'], name='student_att_session_6fd8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['marked_at'], name='student_att_marked__02b02f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('session', 'student')},
        ),
    ]
