# Generated by Django 6.0.2 on 2026-04-19 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _check_constraint_kwargs(expression):
    """Support both Django signatures for CheckConstraint."""
    try:
        models.CheckConstraint(condition=expression, name='__compat_probe__')
        return {'condition': expression}
    except TypeError:
        return {'check': expression}


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_facultyattendance'),
        ('timetable', '0009_rename_timetable_co_semeste_5bbd10_idx_timetable_c_semeste_3e3e21_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='combined_session',
            field=models.ForeignKey(blank=True, help_text='The combined class session for which attendance is being taken (if combined)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='timetable.combinedclasssession'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, help_text='The timetable entry (class) for which attendance is being taken (if not a combined class)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='timetable.timetableentry'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['combined_session', 'date'], name='attendance__combine_a3d6e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(name='attendance_session_exactly_one_class_ref', **_check_constraint_kwargs(models.Q(models.Q(('timetable_entry__isnull', False), ('combined_session__isnull', True)), models.Q(('timetable_entry__isnull', True), ('combined_session__isnull', False)), _connector='OR'))),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('timetable_entry__isnull', False)), fields=('timetable_entry', 'date'), name='attendance_unique_timetable_entry_date'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('combined_session__isnull', False)), fields=('combined_session', 'date'), name='attendance_unique_combined_session_date'),
        ),
    ]
